steps:
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'BUILD=$BUILD_ID'
    args: ['build', '--tag=asia.gcr.io/whattodo-e/p2pserver:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "asia.gcr.io/whattodo-e/p2pserver:$BUILD_ID"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'p2p-server', '--image', 'asia.gcr.io/whattodo-e/p2pserver:$BUILD_ID', '--region', 'us-central1', '--platform', 'managed', '--quiet']
